name: Create Release and Tag

on:
  push:
    branches:
      - main


jobs:
  add_tag:
    runs-on: ubuntu-latest
    env:
      OWNER: dangngoctuan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest milestone
        uses: actions/github-script@v6
        id: milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { issue, repository } = context.payload;
            const list_milestones = await github.request('GET /repos/{owner}/{repo}/milestones', {
              owner: '${{env.OWNER}}',
              repo: repository.name,
              sort: 'due_on',
              direction: 'desc'
            });
            console.log(list_milestones.data)
            const latest_milestone = list_milestones.data[0]
            console.log(latest_milestone)
            return latest_milestone;
      - name: Get information of pull requests in latest milestone
        uses: actions/github-script@v6
        id: pull_requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const latest_milestone = ${{ steps.milestone.outputs.result }}
            console.log(latest_milestone)
            if (latest_milestone == undefined) {
              return []
            }
            const { issue, repository } = context.payload;
            const response = await github.request('GET /search/issues', {
              owner: '${{env.OWNER}}',
              repo: repository.name,
              milestone: latest_milestone.title
            })
            console.log(response)


      # - name: Create Release Tag
      #   uses: actions/github-script@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script:
