name: Create Release and Tag

on:
  push:
    branches:
      - main


jobs:
  add_tag:
    runs-on: ubuntu-latest
    env:
      OWNER: dangngoctuan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest milestone
        uses: actions/github-script@v6
        id: latest_milestone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { issue, repository } = context.payload;
            const list_milestones = await github.request('GET /repos/{owner}/{repo}/milestones', {
              owner: '${{env.OWNER}}',
              repo: repository.name,
              sort: 'due_on',
              direction: 'desc'
            });
            console.log(list_milestones.data)
            const latest_milestone = list_milestones.data[0]
            return latest_milestone;
      - name: Get information of pull requests in latest milestone
        uses: actions/github-script@v6
        id: pull_requests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const latest_milestone = ${{ steps.latest_milestone.outputs.result }};
            if (latest_milestone == undefined) {
              return []
            }
            const { issue, repository } = context.payload;
            const response = await github.request(
              'GET /search/issues?q=milestone:{milestone_title}+type:pr+repo:{owner}/{repo}', {
              owner: '${{env.OWNER}}',
              repo: repository.name,
              milestone_title: latest_milestone.title
            })
            console.log(response)
            const list_pull_requests = response.data.items;
            console.log(list_pull_requests)
            return list_pull_requests;
      - name: Create description for tag
        uses: actions/github-script@v6
        id: tag_description
        with:
          script: |
            const list_pull_requests = ${{ steps.pull_requests.outputs.result }};
            if (list_pull_requests.length == 0) {
              return
            }
            let description = '## What's Changed \n'
            for (const item of list_pull_requests) {
              description += '- ' + item.title + '\n' + '- ' + item.html_url + '\n'
            }

            return description;
      - name: Create Release Tag
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const description = ${{ steps.tag_description.outputs.result }};
            console.log(description)

