name: Create Release and Tag

on:
  push:
    branches:
      - main


jobs:
  release:
    runs-on: ubuntu-latest
    env:
      OWNER: dangngoctuan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest milestone
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script:
            const { issue, repository } = context.payload;
            const list_milestones = await github.request('GET /repos/{owner}/{repo}/milestones', {
              owner: 'dangngoctuan',
              repo: repository.name,
              sort: 'due_on',
              direction: 'desc'
            });
            console.log(list_milestones)
      # - name: Get information of pull requests in latest milestone
      #   uses: actions/github-script@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script:
      # - name: Create Release Tag
      #   uses: actions/github-script@v6
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     script:
