name: Add Reviewer to Pull Request

on:
  issue_comment:
    types: [created]
    branches:
      - main

jobs:
  add_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract username
        uses: actions-ecosystem/action-regex-match@v2
        id: extract
        with:
          text: ${{ github.event.comment.body }}
          regex: '@([a-zA-Z0-9-_]+)'
      - name: Add user as reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const username = '${{ steps.extract.outputs.group1 }}';
            console.log(context)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
