name: Add Pull Request Reviewer

on:
  issue_comment:
    types: [created]
    branches:
      - main

jobs:
  add_pull_request_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract username
        uses: actions-ecosystem/action-regex-match@v2
        id: extract
        with:
          text: ${{ github.event.comment.body }}
          regex: '@([a-zA-Z0-9-_]+) [Rr]eview [Rr]equest'
      - name: Check if user exists
        uses: actions/github-script@v6
        id: check_user
        with:
          script: |
            const username = '${{ steps.extract.outputs.group1 }}';
            const response = await github.request('GET /users/{username}', {
              username: username
            });
            return {
              exists: response.status === 200,
              username: response.data.login
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add user as reviewer
        uses: actions/github-script@v6
        with:
          script: |
            console.log('${{ steps.check_user.outputs.exists }}')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
