name: Add Pull Request Reviewer

on:
  issue_comment:
    types: [created]
    branches:
      - main

jobs:
  add_pull_request_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Extract username
        uses: actions-ecosystem/action-regex-match@v2
        id: extract
        with:
          text: ${{ github.event.comment.body }}
          regex: '@([a-zA-Z0-9-_]+) [Rr]eview [Rr]equest'
      - name: Check if user exists
        uses: actions/github-script@v6
        with:
          script: |
            const username = '${{ steps.extract.outputs.group1 }}';
            const response = await github.request('GET /users/abcfhfjsfks', {
              username: username
            });
            console.log(response)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Add user as reviewer
      #   if: steps.extract.outputs.group1.length > 0
      #   uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const username = '${{ steps.extract.outputs.group1 }}';
      #       console.log(username)
      #       const { issue, repository } = context.payload
      #       const reviewers = [username]
      #       const pull_number = issue.number
      #       const response = await github.request('POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers', {
      #         owner: 'dangngoctuan',
      #         repo: repository.name,
      #         pull_number: pull_number,
      #         reviewers: reviewers
      #       });
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
